### PR TITLE
bug fix: error occured when try to connect already connected VPN

### PR DESCRIPTION
**Pull request by thamaraiselvam**
resolved https://github.com/thecasualcoder/lazy-connect/issues/21

### CODE REVIEW

**Comment by arunvelsriram** [comment]
Thanks for the PR. I don't have access to any IPSec VPNs to test this. 

@jskswamy / @prabhu43 could one of you test and review the PR?

**Comment by jskswamy** [comment]
I still see the following error

```sh
execution error: System Events got an error: Can’t get button "Authentication Settings…" of group 1 of window 1 of process "System Preferences". (-1728)
```

**Comment by thamaraiselvam** [comment]
@jskswamy that is different error Issue created already https://github.com/thecasualcoder/lazy-connect/issues/20

**Comment by thamaraiselvam** [comment]
resolved https://github.com/thecasualcoder/lazy-connect/issues/20

`Can’t get button "Authentication Settings` issue also merged with this PR.

It happens because it could not find the exact name match sometimes. so changed to `contains`

**Comment by jskswamy** [comment]
@thamaraiselvam mojave fix has been merged into master, kindly raise a PR against master

**Pull request closed without merging**
